language: ruby
rvm:
  - 2.6
script:
  - ruby tric.rb
notifications:
  slack:
    secure: "gwbd5hxrvVVdlaSxmNnScZyucQKBz4zeJwA6R5Yl9fcrXD0C+zdHAUztj9V6x1nIzRDtbUoD9ZDMD4cp6+m84qIZSxY6gnizPa1hbmWL96Ht6smC3eByw7zGIh8AFC6jCbCaaUGmOTk85iti/x2E6KMw9nFg7Ex3EV26aFEfwI2Izh+dUm0zWyo/CQ0KddnRRx6U4F3TR2N4FRdkf0eM3KTCT19hWfUG765lO4l0v/1tg5FTs+Vbk12JaXuQt5DvmpyJB9fan2L+en9Lq2d7EeBa/2+l4lfXfCMbO9dSctoDbIPIeyx33j5zQz4/fJ04zbv7zKOQJWG0GyzJwecxx0V1AAosxEjibfDlERzh8wQHtZSLNXCQ1TytNzeEdeF3EjakN4+Lu+rRI8Hb5SLR8c98OXkPG5yV2UMv96iJ8RaL/EElBdBWM2QAWYnKDd+YMZwl9TkyM6LIlLeINF7n62yYGR627UT9UoxKfpBsEqa9gXuxweOHbYvG/kSPw4GNCZmt/LdiNgY1IOYOfOjCq9/6n5S3ZK9HDXEwsnxBluAR8fhzWDiqbjHwUcSNUQTWH+pYPvGTPHSSmAzrB781k2iHNEjZM0YV2vbw5vY/2obtbozWxm7x/XiJqP75vmYnNLrOYJ1OjEfcDpYTtTGxH8U1n1zAo8wsRqodJrKe6ug="
